import type { ComponentType } from 'react';
import type { LucideIcon } from 'lucide-react';
import {
  ShoppingCart,
  Home,
  Briefcase,
  Zap,
  Film,
  Car,
  ShoppingBag,
  Utensils,
  Plane,
  HeartPulse,
  GraduationCap,
  Smile,
  TrendingUp,
  Receipt,
  BadgePercent,
  Landmark,
  MoreHorizontal,
} from 'lucide-react';
import type { Transaction } from './types';

export const CATEGORIES = [
  'Groceries',
  'Rent',
  'Salary',
  'Utilities',
  'Entertainment',
  'Transportation',
  'Shopping',
  'Dining',
  'Travel',
  'Healthcare',
  'Education',
  'Personal Care',
  'Investments',
  'Bills',
  'Fees',
  'Taxes',
  'Other',
];

export const categoryIcons: Record<string, LucideIcon> = {
  Groceries: ShoppingCart,
  Rent: Home,
  Salary: Briefcase,
  Utilities: Zap,
  Entertainment: Film,
  Transportation: Car,
  Shopping: ShoppingBag,
  Dining: Utensils,
  Travel: Plane,
  Healthcare: HeartPulse,
  Education: GraduationCap,
  'Personal Care': Smile,
  Investments: TrendingUp,
  Bills: Receipt,
  Fees: BadgePercent,
  Taxes: Landmark,
  Other: MoreHorizontal,
};

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: '1',
    date: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
    description: 'Monthly Salary',
    amount: 5000,
    type: 'income',
    category: 'Salary',
  },
  {
    id: '2',
    date: new Date(new Date().setDate(new Date().getDate() - 5)).toISOString(),
    description: 'Grocery shopping at Market',
    amount: 150.75,
    type: 'expense',
    category: 'Groceries',
  },
  {
    id: '3',
    date: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
    description: 'Monthly Rent Payment',
    amount: 1200,
    type: 'expense',
    category: 'Rent',
  },
  {
    id: '4',
    date: new Date(new Date().setDate(new Date().getDate() - 3)).toISOString(),
    description: 'Dinner with friends',
    amount: 85.5,
    type: 'expense',
    category: 'Dining',
  },
  {
    id: '5',
    date: new Date(new Date().setDate(new Date().getDate() - 7)).toISOString(),
    description: 'Electricity Bill',
    amount: 75.0,
    type: 'expense',
    category: 'Utilities',
  },
  {
    id: '6',
    date: new Date(new Date().setDate(new Date().getDate() - 10)).toISOString(),
    description: 'New shoes',
    amount: 120.0,
    type: 'expense',
    category: 'Shopping',
  },
];
